---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017-18 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: copy user_variables_os-odl-bgpvpn.yml
  copy:
    src: "user_variables_os-odl-bgpvpn.yml"
    dest: "{{OPENSTACK_OSA_ETC_PATH}}/user_variables_os-odl-bgpvpn.yml"

- name: copy user_variables_os-odl-bgpvpn-ha.yml
  copy:
    src: "{{XCI_FLAVOR}}/user_variables_os-odl-bgpvpn-ha.yml"
    dest: "{{OPENSTACK_OSA_ETC_PATH}}/user_variables_os-odl-bgpvpn-ha.yml"
  when:
  - XCI_FLAVOR == "ha"

- name: copy os-odl-bgpvpn scenario specific openstack_user_config.yml
  copy:
    src: "{{XCI_FLAVOR}}/openstack_user_config.yml"
    dest: "{{OPENSTACK_OSA_ETC_PATH}}/openstack_user_config.yml"

- name: copy os-odl-bgpvpn scenario specific setup-openstack.yml
  copy:
    src: "setup-openstack.yml"
    dest: " {{OPENSTACK_OSA_PATH}}/playbooks"

- name: Copy the OSA not-yet-upstreamed files for Pike
  include: add-osa-files-pike.yml
  when: OPENSTACK_OSA_VERSION == "stable/pike"

- name: Copy the OSA not-yet-upstreamed inventory files for Pike
  include: add-inventory-files-pike.yml
  when: OPENSTACK_OSA_VERSION == "stable/pike"
